PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX biopax3: <http://www.biopax.org/release/biopax-level3.owl#>

PREFIX reactome: <http://www.reactome.org/biopax/59/48887#> 

# Retrieve the hierarchical organisation of the components of a complex and their associated stoichiometric coefficient
SELECT DISTINCT ?complexPart ?comp ?stochioValue

WHERE {
  #VALUES ?complex { reactome:Complex3 reactome:Complex7 reactome:Complex4 reactome:Complex5 reactome:Complex6 reactome:Complex8 reactome:Complex101 reactome:Complex102 }
  #VALUES ?complex { reactome:Complex102 }
  #VALUES ?complex { reactome:Complex1 }
  VALUES ?complex { reactome:Complex100 }
  
  ?complex rdf:type biopax3:Complex .
  ?complex biopax3:component* ?complexPart .
  ?complexPart biopax3:component ?comp .
  OPTIONAL {
    ?complexPart biopax3:componentStoichiometry ?stochio .
    ?stochio biopax3:physicalEntity ?comp .
    ?stochio biopax3:stoichiometricCoefficient ?stochioValue .
  }

}
ORDER BY ?complex
