PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>

PREFIX chebi: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX reactome: <http://www.reactome.org/biopax/79/48887#>
PREFIX uniprot: <http://purl.uniprot.org/uniprot/>

PREFIX dyliss:   <http://www-dyliss.irisa.fr/biopaxComplex/>

DELETE {
  ?complex ?property ?object .

  ?stoichioIdent ?propertyStoichio ?objectStoichio .

  ?xref ?propertyXref ?objectXref .
}

WHERE {
  ?complex rdf:type bp3:Complex .
  ?complex ?property ?object .

  OPTIONAL {
    ?complex bp3:componentStoichiometry ?stoichioIdent .
    ?stoichioIdent ?propertyStoichio ?objectStoichio .
    FILTER NOT EXISTS {
      ?s1 ?p1 ?stoichioIdent .
      ?s2 ?p2 ?stoichioIdent .
      FILTER (?s1 != ?s2)
    }
  }

  OPTIONAL {
    ?complex bp3:xref ?xref .
    ?xref ?propertyXref ?objectXref .
    FILTER NOT EXISTS {
      ?s3 ?p1 ?xref .
      ?s4 ?p2 ?xref .
      FILTER (?s3 != ?s4)
    }
  }

}


