PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>

PREFIX chebi: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chebip: <http://purl.obolibrary.org/obo/chebi/>
PREFIX reactome: <http://www.reactome.org/biopax/78/48887#>
PREFIX uniprot: <http://purl.uniprot.org/uniprot/>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX udb: <http://purl.uniprot.org/database/>
PREFIX obo: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT *
WHERE {
  ?x rdf:type owl:Class .
  #?x ?rel ?val .
  ?x rdfs:label ?label .
  #?x obo:hasDbXref ?xref .
  #?x obo:hasExactSynonym ?s .
  #?x obo:hasRelatedSynonym ?rs .
  #?x chebip:smiles ?smiles .
  ?x rdfs:subClassOf ?y .
  ?x chebip:formula ?formula .
  FILTER NOT EXISTS{?x owl:deprecated "true"^^xsd:boolean .}
  }
LIMIT 100