PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>

$supplementaryPrefixes$

# Retrieve the RDF graph of the direct neighbors of a complex
CONSTRUCT {
  ?complex ?property ?object .

  ?stoichioIdent ?propertyStoichio ?objectStoichio .

  ?xref ?propertyXref ?objectXref .
}

WHERE {
  VALUES ?complex { $complexValue$ }
  
  ?complex ?property ?object .

  OPTIONAL {
    ?complex bp3:componentStoichiometry ?stoichioIdent .
	#?stoichioIdent rdf:type ?stoichioIdentType .
	#?stoichioIdent bp3:physicalEntity ?complexPart .
	#?stoichioIdent bp3:stoichiometricCoefficient ?stoichioValue .
    ?stoichioIdent ?propertyStoichio ?objectStoichio .
  }

  OPTIONAL {
    ?complex bp3:xref ?xref .
    ?xref ?propertyXref ?objectXref .
  }

}
